// build.mjs — bundle all ES modules + font + embedded docs into a single self-contained
// HTML file (../index.html, project root) that runs by double-click (file://), no
// server/modules needed. (The modular dev version lives at html5-port/index.html.)
import { readFileSync, writeFileSync } from 'fs';

const DIR = new URL('./js/', import.meta.url);

// Embed the docs as JS string modules so the in-page doc viewer works offline (file://
// cannot fetch). Bilingual: PORTIERUNG.en.md (English, default) + PORTIERUNG.md (German).
// Written to js/doctext.js so the modular index.html uses it too.
const esc = s => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
const docDe = readFileSync(new URL('../PORTIERUNG.md', import.meta.url), 'utf8');
const docEn = readFileSync(new URL('../PORTIERUNG.en.md', import.meta.url), 'utf8');
writeFileSync(new URL('doctext.js', DIR),
  `// auto-generated by build.mjs from PORTIERUNG.en.md (EN) + PORTIERUNG.md (DE)\n` +
  `const DOC_EN = \`${esc(docEn)}\`;\nconst DOC_DE = \`${esc(docDe)}\`;\nconst DOC_MD = DOC_EN;\n` +
  `export { DOC_EN, DOC_DE, DOC_MD };\n`);

const order = ['palette.js','rtl.js','font8x8.js','pcspeaker.js','sounds.js','vga.js',
  'terrain.js','tank.js','weapons.js','physics.js','ai.js','hud.js','markdown.js',
  'doctext.js','game.js','main.js'];

function strip(src) {
  return src
    .replace(/import\b[\s\S]*?from\s*['"][^'"]+['"]\s*;?/g, '') // drop imports (incl. multi-line)
    .replace(/export\s*\{[\s\S]*?\}\s*;?/g, '')                 // drop `export { ... };` blocks
    .replace(/\bexport\s+default\s+/g, '')
    .replace(/\bexport\s+(class|function|const|let|var)\b/g, '$1'); // inline export decls
}

let bundle = '';
for (const f of order) {
  const src = readFileSync(new URL(f, DIR), 'utf8');
  bundle += `\n// ===== ${f} =====\n` + strip(src) + '\n';
}

const HEAD_STYLE = `
  html,body{margin:0;padding:0;background:#000;height:100%;display:flex;align-items:center;
    justify-content:center;font-family:monospace;overflow:hidden}
  #screen{image-rendering:pixelated;image-rendering:crisp-edges;width:640px;height:480px;background:#000}
  #overlay{position:fixed;inset:0;display:flex;align-items:center;justify-content:center;color:#eee;
    background:rgba(0,0,0,.9);cursor:pointer;text-align:center;z-index:10}
  #overlay .card{max-width:34em;line-height:1.5}#overlay h1{color:#ff4040;letter-spacing:.1em}
  kbd{background:#222;border:1px solid #555;border-radius:3px;padding:0 .3em}
  .btn{display:inline-block;margin-top:1em;padding:.5em 1.1em;background:#2851ff;color:#fff;
    border-radius:5px;cursor:pointer;font-weight:bold;border:1px solid #6f8cff}
  .btn:hover{background:#3f66ff}
  #docview{position:fixed;inset:0;z-index:20;display:none;background:#0d1b3e;color:#e6ecff;
    overflow:auto;padding:2em 1em;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif}
  #docview .doc{max-width:52em;margin:0 auto;line-height:1.6}
  #docview h1,#docview h2,#docview h3{color:#8fb0ff;border-bottom:1px solid #24366b;padding-bottom:.2em}
  #docview h1{color:#ff6a6a}
  #docview code{background:#1b2b57;padding:.1em .35em;border-radius:3px;font-size:.9em}
  #docview pre{background:#101d40;padding:1em;border-radius:6px;overflow:auto}
  #docview pre code{background:none;padding:0}
  #docview table{border-collapse:collapse;margin:1em 0;display:block;overflow:auto}
  #docview th,#docview td{border:1px solid #2d427f;padding:.3em .6em;text-align:left}
  #docview th{background:#1b2b57}
  #docview a{color:#8fb0ff}
  #docview blockquote{border-left:3px solid #3f66ff;margin:1em 0;padding:.2em 1em;background:#101d40}
  #docclose{position:fixed;top:1em;right:1em;z-index:21}
  #doclang{position:fixed;top:1em;right:8.5em;z-index:21}
  #langtoggle{margin-top:.9em;font-size:.85em;opacity:.85;cursor:pointer;text-decoration:underline}`;

// Overlay text is set by main.js per language (English default, German if the browser is
// German); these are just fallbacks in case the script fails.
const OVERLAY = `
<div id="overlay"><div class="card">
  <h1>TankWars&nbsp;V2.07</h1>
  <p id="ovDesc">Faithful HTML5 port of the DOS game by Marko Lindner (1995/96).</p>
  <p id="ovStart"><b>Click to start</b> (enables sound).</p>
  <p id="ovKeys" style="font-size:.85em;opacity:.7"></p>
  <div class="btn" id="docbtn">📖 Show documentation</div>
  <div id="langtoggle">Deutsch</div>
</div></div>
<div id="docview"><div class="btn" id="docclose">✕ Close</div><div class="btn" id="doclang">Deutsch</div><div class="doc" id="doccontent"></div></div>`;

const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>TankWars V2.07 — HTML5 Port</title>
<style>${HEAD_STYLE}</style></head><body>
<canvas id="screen" width="640" height="480"></canvas>${OVERLAY}
<script>
"use strict";
(function(){
${bundle}
})();
</script></body></html>`;

writeFileSync(new URL('../index.html', import.meta.url), html);
console.log('wrote ../index.html (' + (html.length/1024|0) + ' KB, standalone) + js/doctext.js');
